import NavBar from '@/components/layout/navBar/NavBar';
import './globals.css';
import './utils.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import "@fortawesome/fontawesome-svg-core/styles.css"; 

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'FEED ME',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NavBar />
				{children}
			</body>
		</html>
	)
}
