import NavBar from '@/components/layout/navBar/NavBar';
import './globals.css';
import './utils.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/layout/footer/Footer';

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { ReduxProvider } from '@/services/redux';
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'FEED ME',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ReduxProvider>
					<NavBar />
					<main className="websiteWidth navSpace">
						{children}
					</main>
					<Footer />
				</ReduxProvider>
			</body>
		</html>
	)
}
