import React from 'react';
import styles from "./page.module.css";

import db from "@/services/db";
import type { M_MealCategories, M_Restaurant } from '@/services/db/models/category';
import { MealGrid } from '@/features/restaurants';
import Link from 'next/link';
import Rating from '@/components/rating/Rating';

type Props = {
	params: { id: string }
}

export async function generateMetadata({ params }: Props) {
	return {
		title: `FEED ME | ${params.id}`,
		description: 'Generated by create next app',
	}
}

export default async function RestaurantPage({ params }: Props) {
	const { data, menuItems } = await getRestaurantData(params.id);

	return (
		<div className={styles.page}>
			<header className={styles.header}>
				<img src={data.img} alt={data.name} />
				<h1>{data.name}</h1>
				<Rating rating={data.rating} />
			</header>

			<div className={styles.pageRow}>
				<aside className={styles.listContainer}>
					<ul className={styles.menuItemsList}>
						{menuItems.map(item => (
							<li>
								<Link href={`#${item.name}`}>
									{item.name}
								</Link>
							</li>
						))}
					</ul>
				</aside>

				<MealGrid menuItems={menuItems} />

			</div>
		</div>
	)
}

const getRestaurantData = async (restaurantID: string) => {
	const [restaurantsCollection, mealCategoriesCollection] = await Promise.all([db<M_Restaurant>("restaurants"), db<M_MealCategories>("mealCategories")]);

	const data = await restaurantsCollection.findOne({ slug: restaurantID });
	if (!data) throw new Error("Restaurant not found");

	const menuItems = await mealCategoriesCollection.find({ _id: { $in: data.food_category }, active: true }, {projection: {_id: 0}}).toArray();

	return { data, menuItems };
}
